GET http://localhost:5050/recipes

###

GET http://localhost:5050/recipes/64722bba57b4217e70606d8c

###

POST http://localhost:5050/recipes
Content-Type: application/json

{
    "title": "Chicken",
    "ingredients": [
        {
            "ingredient": "chicken",
            "units": "whole",
            "quantity": "1"
        }
    ],
    "instructions": [
        "Dry brine in the refrigerator overnight",
        "roast at 375 for 1 hour"
    ]
}

###

DELETE http://localhost:5050/recipes/64760a9c6c490039f73675f9

###

PUT http://localhost:5050/recipes/64722bba57b4217e70606d8c
Content-Type: application/json

{
    "title": "Roasted Chicken"
}